[package]
name = "meetings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3", features = ["derive"] }
simple_logger = "4.2"
log = "0.4"
rocket = "0.5"
rocket_dyn_templates = { version = "0.1", features = ["tera"] }
sendgrid = "0.19"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[[bin]]
name = "meetings"
path = "src/main.rs"

[[bin]]
name = "cli"
path = "src/cli.rs"
