name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    services:
      surrealdb:
        image: surrealdb/surrealdb:latest
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Show Rust version
      run: rustc -Vv

    - name: Set up cargo cache
      uses: actions/cache@v4
      continue-on-error: false
      with:
        path: |
          ~/.cargo/
          ./target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Build debug version
      run: cargo build --verbose

    - name: Lists tests
      run: cargo test -- --list


    - name: Run tests
      run: |
        cp Rocket.skeleton.toml Rocket.toml
        cargo test --verbose

        #- name: Build release version
        #  run: cargo build --release --verbose

    - name: Check cargo fmt
      run: cargo fmt --check

    - name: Clippy stop at any warning
      run: cargo clippy -- --deny warnings

