name: CI

on:
  push:
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up cargo cache
      uses: actions/cache@v3
      continue-on-error: false
      with:
        path: |
          ~/.cargo/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: ${{ runner.os }}-cargo-

    - name: Build debug version
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose -- --test-threads 1

    - name: Build release version
      run: cargo build --release --verbose

    - name: Check cargo fmt
      run: cargo fmt --check

    - name: Clippy stop at any warning
      run: cargo clippy -- --deny warnings

